name: Auto Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # daily
  workflow_dispatch:     # allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/upstream_owner/upstream_repo.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout master
          git merge upstream/master

      - name: Push changes
        env:
          GH_TOKEN: ${{ secrets.AUTO_SYNC }}
        run: |
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} master
